package com.runescape.revised.content.skill;

public enum SkillType {

	ATTACK, STRENGTH, DEFENSE, RANGE, PRAYER, MAGE, RUNECRAFTING,
	CONSTRUCTION, DUNGEONEERING, HITPOINTS, AGILITY, HERBLORE,
	THIEVING, CRAFTING, FLETCHING, SLAYER, HUNTER, DIVINATION, 
	MINING, SMITHING, FISHING, COOKING, FIREMAKING, WOODCUTTING,
	FARMING, SUMMONING;
}