package com.runescape.revised.content.skill.agility;

public enum Course {

	GNOME_STRONGHOLD, ADVANCED_GNOME_STRONGHOLD, BRIMHAVEN, AGILITY_PYRAMID, PENGUIN, BARBARIAN_OUTPOST,
	ADVANCED_BARBARIAN_OUTPOST, APE_ATOLL, WILDERNESS, WEREWOLF, BANDOS, DORGESH_KAAN, WEREWOLF_SKULLBALL, GNOME_BALL,
	TOY_MOUSE, BLAST_FURNACE, LIVID_FARM;
}